### ISSUE TITLE
Tweeten prevents power management to turn off the monitor

### ISSUE THREAD

**Issue by withinpipo** [MehediH/Tweeten#235] opened 2021-04-30 01:35 UTC
C:\Windows\system32>powercfg /requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume4\Users\withinpipo\AppData\Local\Programs\Tweeten\Tweeten.exe
Video Wake Lock

Closing the app then relaunching it give me the lock right away

**Comment by jetuser** [comment] 2021-05-01 18:05
I'm seeing the same thing myself. I can't seem to narrow down a specific behavior that causes this, seemingly random.

**Comment by MehediH** [comment] 2021-05-01 18:12
Duplicate of #231

**Closed by MehediH** 2021-05-01 18:12 UTC
