### ISSUE TITLE
proxy setting is needed

### ISSUE THREAD

**Issue by deadjoker** [MehediH/Tweeten#178] opened 2020-05-19 10:26 UTC
Many people can only visit twitter by http proxy or socket. But I don't find any option can be set the proxy. I think it's more convenient if tweeten has a proxy setting.

**Comment by MehediH** [comment] 2020-05-19 10:30
Hi, how would this work? Would you just enter the proxy URL/IP?

**Comment by deadjoker** [comment] 2020-05-19 10:51
From my point of view, it's not a wise choice for me to connect to a VPN.
It's a good idea to set the proxy by entering an url :)

**Comment by kaka77** [comment] 2020-11-30 05:00
> 许多人只能通过http代理或套接字访问Twitter。但是我找不到可以设置代理的任何选项。我认为如果tweeten设置代理服务器会更方便。

yep

**Comment by kaka77** [comment] 2020-11-30 05:00
> Many people can only visit twitter by http proxy or socket. But I don't find any option can be set the proxy. I think it's more convenient if tweeten has a proxy setting.

yep   +1

**Comment by MehediH** [comment] 2021-07-18 09:02
Duplicate of #56

**Closed by MehediH** 2021-07-18 09:02 UTC
Labels: enhancement
