### ISSUE TITLE
Missing profile picture on the column...

### ISSUE THREAD

**Issue by RalphyLikes** [MehediH/Tweeten#78] opened 2018-04-27 14:55 UTC
I have this bug for couple of days now, please fix this. (Screenshot)

![capture](https://user-images.githubusercontent.com/38789895/39368824-3faf8bfc-4a6d-11e8-86f3-59f5cd5cb4f1.PNG)

**Comment by Stanzilla** [comment] 2018-05-02 20:46
Duplicate of https://github.com/MehediH/Tweeten/issues/77

**Closed** 2018-05-10 20:29 UTC
