### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SesaXD** [MehediH/Tweeten#133] opened 2018-11-06 12:27 UTC
i was just using tweeten as everyday but i pressed random keys and since that this appears and i can't see what i am tweeting, known issue??[](url)
![screenshot_2531](https://user-images.githubusercontent.com/44805960/48064293-ad7a1200-e1c7-11e8-97be-6167bf2e3139.png)

**Comment by ItaloKnox** [comment] 2018-11-06 13:52
This started happening to me as well early this morning when I updated TweetDeck (by clicking on the glowing cog icon). The only workaround, for now, is to ctrl+a your tweet to see it selected or change to the white theme. None of the black themes are currently working as intended.

**Comment by Astragali** [comment] 2018-11-06 14:49
Yep, I'm also getting this in the dark theme; light works fine.

**Comment by XSilverlink** [comment] 2018-11-13 17:22
I had this issue but it fixed itself. I had the issue still with adding GIFS though.
Enabled Custom CSS and added this:

```
html.dark input, html.dark select {
    color: black !important;
}
```

That fixed the input box for GIFs atleast

**Comment by MehediH** [comment] 2018-11-22 09:20
As long as you are at 4.6.1 this should be fixed.

**Closed by MehediH** 2018-11-22 09:20 UTC
