### ISSUE TITLE
Selecting text and dragging into other application makes TweetDeck UI unclickable

### ISSUE THREAD

**Issue by ngdio** [MehediH/Tweeten#221] opened 2021-03-23 22:02 UTC
Every time I select a part of a tweet and drag it into my browser's taskbar, the TweetDeck UI becomes unclickable. It is clearly still running as new tweets are loading, but it doesn't take any mouse or keyboard input. No hover actions either, cursor also freezes and doesn't change based on what I'm hovering. It doesn't matter at which application I'm dropping the selection, I always have the same issue. Selecting and drag-and-dropping within Tweeten works, though.

I have experienced and reproduced this issue among two PCs, Windows 10 and macOS Big Sur.

**Comment by MehediH** [comment] 2021-03-23 22:07
Can you send a video showing this in action? Can't reproduce this on my end.

**Comment by ngdio** [comment] 2021-03-23 23:16
Sure. I realised while recording that it doesn't actually happen every time, but probably more like ~70% percent. That it's scrolling sidewards is actually new, I suppose it might depend on where I move the mouse.

https://user-images.githubusercontent.com/13526985/112230766-b6070200-8c35-11eb-98a8-72eb349a7535.mp4

I suspect it might be due to Tweeten/Electron not actually realising that the drop event has happened, and the app still thinks I'm dragging indefinitely, since it's scrolling to the right when I'm hovering the side of the window. But that's just an uneducated guess.

**Comment by MehediH** [comment] 2021-03-23 23:25
Thanks for that! If you are on the Discord (https://discord.gg/fynzcdfwhD), can you try the upcoming update and see if you can repro this on there?

**Comment by MehediH** [comment] 2021-07-18 08:41
This should be fixed in newer versions of Tweeten, please let me know if this isn't the case.

**Closed by MehediH** 2021-07-18 08:41 UTC
