### ISSUE TITLE
5.3.0 prevents M1 Mac Mini turn off display

### ISSUE THREAD

**Issue by tapetum** [MehediH/Tweeten#228] opened 2021-04-07 23:35 UTC
On Mac Mini M1 with Big Sur 11.2.3, Tweeten 5.3.0 prevents the Energy Saver from turning off the display when prevent computer from sleeping is checked. If the prevent computer from sleeping is unchecked, the computer does sleep. Prior versions allowed the display to be turned off without sleeping the computer. 
![image](https://user-images.githubusercontent.com/11934138/113947337-ad7f0180-97c7-11eb-8854-68043b1140a8.png)

**Comment by MehediH** [comment] 2021-07-18 08:36
Duplicate of #231

**Closed by MehediH** 2021-07-18 08:36 UTC

**Comment by tapetum** [comment] 2021-07-24 03:21
Same issue for me with 5.4.0.
