### ISSUE TITLE
Tweeten window doesn't remember size/placement after restoring from maximized

### ISSUE THREAD

**Issue by StefanGagne** [MehediH/Tweeten#174] opened 2020-05-16 19:30 UTC
My monitor is 2560x1440, with a second monitor at 1600x900. I normally keep Tweeten on the primary monitor, with narrowest and tallest size an pushed off to the right of the screen. (See attachment 1.) If I maximize the window so I can see all my columns, once I restore it back to normal, it's no longer narrow and tall and instead is 1707x960 pixels in size and centered on my monitor. (See attachment 2.)

This is using Tweeten 5.0.3, which I upgraded to today by downloading it from your website.

![tweeten1](https://user-images.githubusercontent.com/35638264/82128570-2f1e0900-978a-11ea-908e-dd9894f6b067.jpg)

![tweeten2](https://user-images.githubusercontent.com/35638264/82128573-2f1e0900-978a-11ea-9bcf-386da8a31f71.jpg)

**Comment by Spilyay** [comment] 2020-05-18 11:26
I don't use a Multiple display setup but the same/similar problem happens here with Scale: 150%, Resolution: 1920x1080 and Orientation: Landscape for Windows 10 and Tweeten 5.0.3.

**Comment by MehediH** [comment] 2020-05-27 19:25
@Spilyay Could you please share the behavior you experienced on Tweeten 5.0.2? Even when I am running 5.0.2, snapping the app to the side, maximizing, and then unmaximizing, it does not restore back to the previous unmaximized state. This also seems to be the behavior for most Windows apps.

**Comment by StefanGagne** [comment] 2020-05-27 19:53
But every single app I'm running right now (firefox, windows explorer, discord, notepad, spotify, evernote, steam) DOES restore back to the previous unmaximized state. I'd say it's the possible, most windows apps remember their size and positioning and snap back to it once unmaximized.

5.0.2 did the same; if I had it in a narrow column like my first image above, then maximized, when I restored it it'd go right back to being a narrow column on the right side of the screen. But since 5.0.3 it forces itself to be a wide window, as per the second screenshot.

**Comment by MehediH** [comment] 2020-05-27 19:56
@StefanGagne Are you using aero snap? Or are you just manually resizing it yourself to the side? It didn't work for me with Discord, Edge, Slack.

**Comment by StefanGagne** [comment] 2020-05-27 20:03
I'm manually resizing it. I don't use snap. All my windows pop back to the same position and size they were in when I un-maximize them.

**Comment by MehediH** [comment] 2020-05-27 20:05
Yep, in that case the next version of Tweeten will fix this issue. But the "issue" with aero snap will persist.

**Comment by EdwardWongHau** [comment] 2020-06-24 11:28
The 5.0.4 broke somethings, cause with 5.0.3 I didn't have this issue, now I have :)

Tweeten windows does not remember size and placement. I got 2 screens, and use Aero swap. But whatever screen I put Tweeten on, aero swap or not. At each new start the windows is by default in the middle of the main screen.

**Comment by StefanGagne** [comment] 2020-06-24 13:05
Interestingly it's the opposite here -- the situation is now fixed. Maximize and Restore behave as they once did. Tweeten DOES start out much larger than it should, it's not remembering position/size between shutdown and startup, but once you manually re-size it the window snaps back to where it should be when you max/unmax.

**Comment by MehediH** [comment] 2020-06-24 13:37
@EdwardWongHau Most Windows apps don't save state when you use aero snap, Tweeten is the same. If you manually put it to the desired position, it should work.

There's currently a bug where putting it at the edge of the monitor resets the window state because Tweeten think it's not visible in your monitor. This will be fixed in the next release. 

@StefanGagne the issue you are stating sounds more of a Windows DPI issue, if you disable Windows' 'Let Windows try to fix apps so they're not blurry' option, that might fix it.

**Comment by MehediH** [comment] 2020-07-04 19:24
@EdwardWongHau Are you able to send me an email at meh@builtbymeh.com? I want to share a new build with you that possibly solves the problem, but just need to verify.

**Comment by EdwardWongHau** [comment] 2020-07-04 21:40
Here I am. I will gladly help you

Le sam. 4 juil. 2020 à 21:24, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 10:25
@EdwardWongHau Can you please try download this and see if the issue with Tweeten not remembering state still occurs? https://www.dropbox.com/t/9UQ1UNMAGrfJoryP

**Comment by EdwardWongHau** [comment] 2020-07-05 10:41
Hello,

It works, but only after you click on "Save Settings" in the settings menu.
Before that, it doesn't remember window size and placement, whether or not
you use aero swap or place it manually.

Le dim. 5 juil. 2020 à 12:25, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 10:48
Could you please provide me with steps to reproduce this issue? It works fine here for me, without needing to Save Settings.

**Comment by EdwardWongHau** [comment] 2020-07-05 11:19
After further investigations here is what I can say.

   - If the option "Use default windows title bar" is checked
      - It remember the windows size and position if placed manually
      - It won't remember the window size and position if placed with aero
      swap
      - I don't have to click on "Save settings" to works
      - Same behaviour on main and second screen
   - If the option "Use default windows title bar" is not checked
      - It remember the windows size and position if placed manually
      - It remember the window size and position if placed with aero swap
      - I have to click on "Save settings" to works
      - Same behaviour on main and second screen


Step to reproduce :

   1. Launching Tweeten from the taskbar shortcut
   2. Place the window where I want, using aeroswap on my second screen
   3. Resizing it
   4. Open settings menu and click "Save Settings"
   5. Close Tweeten
   6. On next launch, the window is where it was.

I hope it helps.

Le dim. 5 juil. 2020 à 12:48, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 13:33
Sorry, I am a bit confused -- does the app save the window state when you place it manually, without using aero swap?

**Comment by EdwardWongHau** [comment] 2020-07-05 13:48
Yes automatically if "Use default windows title bar" is checked in the
settings. If not, then I have to click on "Save settings" to save the
window state.


Le dim. 5 juil. 2020 à 15:33, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 13:51
Can you confirm you are running v5.0.4? I am still unable to reproduce the issue. Could you also please share a screenshot of where the window is placed on your screen?

**Comment by EdwardWongHau** [comment] 2020-07-05 14:03
Here my desktop. And I join a backup of my settings
[image: Sans titre.jpg]

Le dim. 5 juil. 2020 à 15:51, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 14:04
The screenshot does not show, can you upload via GitHub instead of email?

**Comment by EdwardWongHau** [comment] 2020-07-05 14:09
I don't know how to use github, so here a Imgur link
https://imgur.com/a/Wt8AsGN

Le dim. 5 juil. 2020 à 16:04, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 14:22
Please try this build https://www.dropbox.com/t/y34QLoF5j506oJuQ

**Comment by EdwardWongHau** [comment] 2020-07-05 14:30
Ouch, do not work at all. got this error a launch
https://imgur.com/a/uzfpXZk

Le dim. 5 juil. 2020 à 16:22, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 14:40
Sorry please try this now, should be fixed: https://www.dropbox.com/t/iC6f6eyDJZLQgGkN

**Comment by EdwardWongHau** [comment] 2020-07-05 14:57
With the last build :

   - If the option "Use default windows title bar" is checked
      - It remember the windows size and position if placed manually
      - It remember the window size and position if placed with aero swap
      - I don't have to click on "Save settings" to works
      - Same behaviour on main and second screen
   - If the option "Use default windows title bar" is not checked
      - It remember the windows size and position if placed manually
      - It remember the window size and position if placed with aero swap
      - I have to click on "Save settings" to works
      - Same behaviour on main and second screen

So, it works perfectly with "Use default windows title bar" checked, not
quite without cause you still have to click on "Save settings" to remember
the window state, not a big deal if you ask me.

Le dim. 5 juil. 2020 à 16:40, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 20:29
Thank you, that was very helpful! Please try this out: https://www.dropbox.com/t/MYhdjjID3QeU2otT

**Comment by EdwardWongHau** [comment] 2020-07-05 21:25
Now it works perfectly, with or without "Use default windows title bar"
checked. Well done. Thanks for your work on this very useful app.

Le dim. 5 juil. 2020 à 22:29, Mehedi Hassan <notifications@github.com> a
écrit :

**Comment by MehediH** [comment] 2020-07-05 21:26
Amazing, thank you for your help today!

**Closed by MehediH** 2020-07-05 21:26 UTC
Labels: bug
